plugin: remove compile failed numainfo
Why we should bear the compile fail *every* time, looks like:
numainfo.c:7:18: fatal error: numa.h: No such file or directory
 #include <numa.h>

We need to take responsibility for our code, but not leave it alone
after pushing them to remote.

Signed-off-by: Hailong Liu <liuhailong@linux.alibaba.com>